import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.whiteA700,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.indigo400,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(19.h),
          ),
          shadowColor: appTheme.indigoA400.withOpacity(0.25),
          elevation: 12,
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 4,
        space: 4,
        color: appTheme.gray40001,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.black900,
          fontSize: 16.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.blueGray40002,
          fontSize: 12.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        displayLarge: TextStyle(
          color: appTheme.blue900,
          fontSize: 52.fSize,
          fontFamily: 'PT Sans Caption',
          fontWeight: FontWeight.w700,
        ),
        displaySmall: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 36.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        headlineSmall: TextStyle(
          color: appTheme.blueGray90001,
          fontSize: 24.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        labelLarge: TextStyle(
          color: appTheme.blueGray90001,
          fontSize: 12.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        labelSmall: TextStyle(
          color: appTheme.indigo100,
          fontSize: 8.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w500,
        ),
        titleLarge: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 20.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        titleMedium: TextStyle(
          color: appTheme.blueGray90001,
          fontSize: 16.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w500,
        ),
        titleSmall: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 14.fSize,
          fontFamily: 'Lato',
          fontWeight: FontWeight.w600,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light();
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  // Blue
  Color get blue100 => Color(0XFFBAD6FF);
  Color get blue900 => Color(0XFF184A9E);

  // BlueGray
  Color get blueGray100 => Color(0XFFD9D9D9);
  Color get blueGray200 => Color(0XFFB8B8D2);
  Color get blueGray400 => Color(0XFF878787);
  Color get blueGray40001 => Color(0XFF828290);
  Color get blueGray40002 => Color(0XFF858597);
  Color get blueGray600 => Color(0XFF398A80);
  Color get blueGray700 => Color(0XFF4F4E68);
  Color get blueGray900 => Color(0XFF363636);
  Color get blueGray90001 => Color(0XFF1F1F39);

  // DeepPurple
  Color get deepPurple300 => Color(0XFF9065BE);
  Color get deepPurple50 => Color(0XFFEFE0FF);

  // Gray
  Color get gray100 => Color(0XFFF4F3FD);
  Color get gray300 => Color(0XFFE0DEEC);
  Color get gray30001 => Color(0XFFDDDDDD);
  Color get gray400 => Color(0XFFBBB5B3);
  Color get gray40001 => Color(0XFFC4C4C4);
  Color get gray40002 => Color(0XFFB1B1B1);
  Color get gray40003 => Color(0XFFADADB2);
  Color get gray50 => Color(0XFFF8F2FF);
  Color get gray5001 => Color(0XFFF3FBFF);
  Color get gray600 => Color(0XFF7F7F7F);
  Color get gray700 => Color(0XFF5B5959);
  Color get gray80099 => Color(0X993C3C43);
  Color get gray900 => Color(0XFF1B0C3D);

  // Indigo
  Color get indigo100 => Color(0XFFC7C5D4);
  Color get indigo400 => Color(0XFF5063BF);
  Color get indigo50 => Color(0XFFEAEAFF);
  Color get indigo5001 => Color(0XFFE6E5ED);
  Color get indigo5002 => Color(0XFFE7E4F9);
  Color get indigo5003 => Color(0XFFE9E7F1);
  Color get indigo900 => Color(0XFF250C5A);
  Color get indigoA400 => Color(0XFF3D5CFF);
  Color get indigoA700 => Color(0XFF173AFF);

  // LightBlue
  Color get lightBlue50 => Color(0XFFCEECFE);

  // Orange
  Color get orangeA700 => Color(0XFFFF6905);

  // Pink
  Color get pinkA100 => Color(0XFFEC7B9C);

  // Purple
  Color get purple200 => Color(0XFFEC7BD3);

  // Red
  Color get red50 => Color(0XFFFFEBF0);
  Color get red5001 => Color(0XFFFFE7EE);
  Color get red5002 => Color(0XFFFFE7F7);

  // Redd
  Color get red6006d => Color(0X6DF82222);

  // Teal
  Color get teal100 => Color(0XFFBAE0DB);
  Color get teal50 => Color(0XFFD8FFEF);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);

  // Yellow
  Color get yellow100 => Color(0XFFFDFBBE);
  Color get yellow500 => Color(0XFFF9F01F);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
